/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NorthAtomButton {
    'interaction': string;
    'link': string;
    'state': "enabled" | "disabled";
    'type': "primary" | "secondary" | "text-only" | "icon-only" | "submit";
  }
  interface NorthAtomCheckbox {
    'name': string;
    'value': string;
  }
}

declare global {


  interface HTMLNorthAtomButtonElement extends Components.NorthAtomButton, HTMLStencilElement {}
  var HTMLNorthAtomButtonElement: {
    prototype: HTMLNorthAtomButtonElement;
    new (): HTMLNorthAtomButtonElement;
  };

  interface HTMLNorthAtomCheckboxElement extends Components.NorthAtomCheckbox, HTMLStencilElement {}
  var HTMLNorthAtomCheckboxElement: {
    prototype: HTMLNorthAtomCheckboxElement;
    new (): HTMLNorthAtomCheckboxElement;
  };
  interface HTMLElementTagNameMap {
    'north-atom-button': HTMLNorthAtomButtonElement;
    'north-atom-checkbox': HTMLNorthAtomCheckboxElement;
  }
}

declare namespace LocalJSX {
  interface NorthAtomButton extends JSXBase.HTMLAttributes<HTMLNorthAtomButtonElement> {
    'interaction'?: string;
    'link'?: string;
    'state'?: "enabled" | "disabled";
    'type'?: "primary" | "secondary" | "text-only" | "icon-only" | "submit";
  }
  interface NorthAtomCheckbox extends JSXBase.HTMLAttributes<HTMLNorthAtomCheckboxElement> {
    'name'?: string;
    'value'?: string;
  }

  interface IntrinsicElements {
    'north-atom-button': NorthAtomButton;
    'north-atom-checkbox': NorthAtomCheckbox;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


